
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="documents.css"/>
</head>
<body>
    {{-- $voyages[0]->planned_discharging_port --}}
<div style="position:absolute;top:0.71in;left:0.86in;width:0.81in;line-height:0.22in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:MS Mincho;color:#000000">第</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:MS-PMincho;color:#000000">１</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:MS Mincho;color:#000000">号様式</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.11in;left:3.36in;width:2.57in;line-height:0.21in;"><DIV style="position:relative; left:0.62in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS Mincho;color:#000000">入</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.11in;left:3.36in;width:2.57in;line-height:0.21in;"><DIV style="position:relative; left:0.98in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS Mincho;color:#000000">出</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.11in;left:3.36in;width:2.57in;line-height:0.21in;"><DIV style="position:relative; left:1.33in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS Mincho;color:#000000">港</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.11in;left:3.36in;width:2.57in;line-height:0.27in;"><DIV style="position:relative; left:1.69in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:MS Mincho;color:#000000">届</span><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:TimesNewRomanPS-BoldMT;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:TimesNewRomanPSMT;color:#000000">GENERAL DECLARATION</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.90in;left:5.45in;width:0.30in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">到着</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.03in;left:5.45in;width:0.38in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Arrival</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.90in;left:7.22in;width:0.30in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">出発</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.03in;left:7.22in;width:0.52in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Departure</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:1.88in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_1.png" />
<img style="position:absolute;top:1.88in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_2.png" />
<img style="position:absolute;top:1.88in;left:4.96in;width:0.40in;height:0.01in" src="documents/general_declaration/vi_3.png" />
<img style="position:absolute;top:1.88in;left:5.36in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_4.png" />
<img style="position:absolute;top:1.88in;left:5.36in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_5.png" />
<img style="position:absolute;top:1.88in;left:6.73in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_6.png" />
<img style="position:absolute;top:1.88in;left:6.73in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_7.png" />
<img style="position:absolute;top:1.88in;left:6.73in;width:0.40in;height:0.01in" src="documents/general_declaration/vi_8.png" />
<img style="position:absolute;top:1.88in;left:7.13in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_9.png" />
<img style="position:absolute;top:1.88in;left:7.13in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_10.png" />
<img style="position:absolute;top:1.89in;left:4.95in;width:0.01in;height:0.29in" src="documents/general_declaration/vi_11.png" />
<img style="position:absolute;top:1.89in;left:5.36in;width:0.01in;height:0.29in" src="documents/general_declaration/vi_12.png" />
<img style="position:absolute;top:1.89in;left:6.73in;width:0.01in;height:0.29in" src="documents/general_declaration/vi_13.png" />
<img style="position:absolute;top:1.89in;left:7.13in;width:0.01in;height:0.29in" src="documents/general_declaration/vi_14.png" />
<div style="position:absolute;top:2.23in;left:0.94in;width:2.06in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">1. </span></SPAN><br/></div>
<div style="position:absolute;top:2.23in;left:0.94in;width:2.06in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船舶の名称</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">種類及び信号符字</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.36in;left:1.15in;width:1.67in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Name, Type and Ca</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ll Sign of ship</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN>{{$ship_lists[0]->vessel_name}}     {{$ship_lists[0]->call_number}}</div>
<div style="position:absolute;top:2.23in;left:5.03in;width:1.16in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">2. </span></SPAN><br/></div>
<div style="position:absolute;top:2.23in;left:5.03in;width:1.16in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">到着港</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">／</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">出発港</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.36in;left:5.24in;width:1.20in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Port of a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">rrival/departure</span><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPS-ItalicMT;color:#000000"> </span><br/></SPAN>{{$voyages[0]->planned_loading_port}}</div>
<div style="position:absolute;top:2.23in;left:6.80in;width:1.43in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">3. </span></SPAN><br/></div>
<div style="position:absolute;top:2.23in;left:6.80in;width:1.43in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">到着日時</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">／</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">出発日時</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.36in;left:7.00in;width:1.52in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Date-</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">time of a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">rrival /departure</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.18in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_15.png" />
<img style="position:absolute;top:2.18in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_16.png" />
<img style="position:absolute;top:2.18in;left:0.87in;width:4.08in;height:0.01in" src="documents/general_declaration/vi_17.png" />
<img style="position:absolute;top:2.18in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_18.png" />
<img style="position:absolute;top:2.18in;left:4.96in;width:0.40in;height:0.01in" src="documents/general_declaration/vi_19.png" />
<img style="position:absolute;top:2.18in;left:5.36in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_20.png" />
<img style="position:absolute;top:2.18in;left:5.37in;width:1.36in;height:0.01in" src="documents/general_declaration/vi_21.png" />
<img style="position:absolute;top:2.18in;left:6.73in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_22.png" />
<img style="position:absolute;top:2.18in;left:6.73in;width:0.40in;height:0.01in" src="documents/general_declaration/vi_23.png" />
<img style="position:absolute;top:2.18in;left:7.13in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_24.png" />
<img style="position:absolute;top:2.18in;left:7.14in;width:1.36in;height:0.01in" src="documents/general_declaration/vi_25.png" />
<img style="position:absolute;top:2.18in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_26.png" />
<img style="position:absolute;top:2.19in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_27.png" />
<img style="position:absolute;top:2.19in;left:4.95in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_28.png" />
<img style="position:absolute;top:2.19in;left:6.73in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_29.png" />
<img style="position:absolute;top:2.19in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_30.png" />
<div style="position:absolute;top:2.85in;left:0.94in;width:0.88in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">4. </span></SPAN><br/></div>
<div style="position:absolute;top:2.86in;left:0.94in;width:0.88in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船舶の国籍</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.99in;left:1.15in;width:0.94in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Na</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">tionality of ship</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN>日本籍</div>
<div style="position:absolute;top:2.85in;left:2.99in;width:0.88in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">5. </span></SPAN><br/></div>
<div style="position:absolute;top:2.86in;left:2.99in;width:0.88in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船長の氏名</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.99in;left:3.19in;width:0.82in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Name of Master</span><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPS-ItalicMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.85in;left:5.03in;width:1.43in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">6. </span></SPAN><br/></div>
<div style="position:absolute;top:2.86in;left:5.03in;width:1.43in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">前寄港地</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">／</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">次寄港地</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.99in;left:5.24in;width:1.80in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Port a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">rrived from/Port of destination</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN>{{$voyages[0]->planned_discharging_port}}</div>
<img style="position:absolute;top:2.81in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_31.png" />
<img style="position:absolute;top:2.81in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_32.png" />
<img style="position:absolute;top:2.81in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_33.png" />
<img style="position:absolute;top:2.81in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_34.png" />
<img style="position:absolute;top:2.81in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_35.png" />
<img style="position:absolute;top:2.81in;left:4.96in;width:1.77in;height:0.01in" src="documents/general_declaration/vi_36.png" />
<img style="position:absolute;top:2.81in;left:6.73in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_37.png" />
<img style="position:absolute;top:2.81in;left:6.73in;width:1.77in;height:0.01in" src="documents/general_declaration/vi_38.png" />
<img style="position:absolute;top:2.81in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_39.png" />
<img style="position:absolute;top:2.81in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_40.png" />
<img style="position:absolute;top:2.81in;left:2.91in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_41.png" />
<img style="position:absolute;top:2.81in;left:4.95in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_42.png" />
<img style="position:absolute;top:2.81in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_43.png" />
<div style="position:absolute;top:3.48in;left:0.94in;width:2.25in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">7. </span></SPAN><br/></div>
<div style="position:absolute;top:3.49in;left:0.94in;width:2.25in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船籍港</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">登録年月日</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">及び船舶番号</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:3.45in;left:2.26in;width:0.12in;line-height:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000">※</span><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.62in;left:1.15in;width:1.63in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Cer</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">tificate of registry</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Port; Date</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.62in;left:2.75in;width:0.12in;line-height:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000">※</span><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.62in;left:2.82in;width:0.55in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">; Number</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">）</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.48in;left:5.03in;width:2.51in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">8. </span></SPAN><br/></div>
<div style="position:absolute;top:3.49in;left:5.03in;width:2.51in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船舶の代理人の氏名又は名称及び住所</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:3.62in;left:5.24in;width:1.66in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Name and addre</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ss of ship’s agent</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.32in;left:5.17in;width:2.34in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船舶の運航者の氏名又は名称及び住所</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.45in;left:5.24in;width:1.82in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Name and addre</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ss of ship’s Operator</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.44in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_44.png" />
<img style="position:absolute;top:3.44in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_45.png" />
<img style="position:absolute;top:3.44in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_46.png" />
<img style="position:absolute;top:3.44in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_47.png" />
<img style="position:absolute;top:3.44in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_48.png" />
<img style="position:absolute;top:3.44in;left:4.96in;width:3.54in;height:0.01in" src="documents/general_declaration/vi_49.png" />
<img style="position:absolute;top:3.44in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_50.png" />
<img style="position:absolute;top:3.44in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_51.png" />
<img style="position:absolute;top:3.44in;left:4.95in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_52.png" />
<img style="position:absolute;top:3.44in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_53.png" />
<div style="position:absolute;top:4.11in;left:0.94in;width:0.68in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">9. </span></SPAN><br/></div>
<div style="position:absolute;top:4.12in;left:0.94in;width:0.68in;line-height:0.18in;"><DIV style="position:relative; left:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">総トン数</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.25in;left:1.15in;width:0.73in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Gross tonnage</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN>{{$ship_lists[0]->gross_ton}}</div>
<div style="position:absolute;top:4.11in;left:2.99in;width:0.74in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">10. </span></SPAN><br/></div>
<div style="position:absolute;top:4.12in;left:2.99in;width:0.74in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">純トン数</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.25in;left:3.26in;width:0.62in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Net t</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">onnage</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.07in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_54.png" />
<img style="position:absolute;top:4.07in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_55.png" />
<img style="position:absolute;top:4.07in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_56.png" />
<img style="position:absolute;top:4.07in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_57.png" />
<img style="position:absolute;top:4.07in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_58.png" />
<img style="position:absolute;top:4.07in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_59.png" />
<img style="position:absolute;top:4.07in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_60.png" />
<img style="position:absolute;top:4.07in;left:2.91in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_61.png" />
<img style="position:absolute;top:4.07in;left:4.95in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_62.png" />
<img style="position:absolute;top:4.07in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_63.png" />
<div style="position:absolute;top:4.74in;left:0.94in;width:2.12in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">11. </span></SPAN><br/></div>
<div style="position:absolute;top:4.74in;left:0.94in;width:2.12in;line-height:0.18in;"><DIV style="position:relative; left:0.23in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">港における</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船舶の位置</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">停泊地</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">）</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.88in;left:1.21in;width:2.35in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Pos</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">iti</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">on of the ship in the port</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">berth or station</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">）</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.69in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_64.png" />
<img style="position:absolute;top:4.69in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_65.png" />
<img style="position:absolute;top:4.69in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_66.png" />
<img style="position:absolute;top:4.69in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_67.png" />
<img style="position:absolute;top:4.69in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_68.png" />
<img style="position:absolute;top:4.69in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_69.png" />
<img style="position:absolute;top:4.70in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_70.png" />
<img style="position:absolute;top:4.70in;left:4.95in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_71.png" />
<img style="position:absolute;top:4.70in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_72.png" />
<div style="position:absolute;top:5.37in;left:0.94in;width:6.88in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">12. </span></SPAN><br/></div>
<div style="position:absolute;top:5.37in;left:0.94in;width:6.88in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">航海に関する簡潔な細目</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">寄港地及び寄港予定地</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">積載された</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">ままの</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">貨物が荷揚げされる予定の港に下線を付す</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。）</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.50in;left:1.21in;width:5.84in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Brief particulars of </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">voyage</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">previous and subse</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">quent ports of ca</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ll; u</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">nderline where remaining </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">car</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">go wi</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ll be discharged</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">）</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:5.32in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_73.png" />
<img style="position:absolute;top:5.32in;left:0.87in;width:4.08in;height:0.01in" src="documents/general_declaration/vi_74.png" />
<img style="position:absolute;top:5.32in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_75.png" />
<img style="position:absolute;top:5.32in;left:4.96in;width:3.54in;height:0.01in" src="documents/general_declaration/vi_76.png" />
<img style="position:absolute;top:5.32in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_77.png" />
<img style="position:absolute;top:5.33in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_78.png" />
<img style="position:absolute;top:5.33in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_79.png" />
<div style="position:absolute;top:6.00in;left:0.94in;width:1.73in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">13. </span></SPAN><br/></div>
<div style="position:absolute;top:6.00in;left:0.94in;width:1.73in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">貨物に関する簡潔な記述</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.13in;left:1.21in;width:1.46in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Brief description of the </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">cargo</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN>{{$voyages[0]->cargo_description}}を{{$voyages[0]->cargo_amount}}トン</div>
<img style="position:absolute;top:5.95in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_80.png" />
<img style="position:absolute;top:5.95in;left:0.87in;width:7.63in;height:0.01in" src="documents/general_declaration/vi_81.png" />
<img style="position:absolute;top:5.95in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_82.png" />
<img style="position:absolute;top:5.96in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_83.png" />
<img style="position:absolute;top:5.96in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_84.png" />
<div style="position:absolute;top:6.63in;left:0.94in;width:1.84in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">14. </span></SPAN><br/></div>
<div style="position:absolute;top:6.63in;left:0.94in;width:1.84in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">乗組員の数</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船長を含む</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。）</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.76in;left:1.21in;width:1.51in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Number of crew</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">incl. master</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">）</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.63in;left:2.99in;width:0.81in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">15. </span></SPAN><br/></div>
<div style="position:absolute;top:6.63in;left:2.99in;width:0.81in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">旅客の数</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.76in;left:3.26in;width:1.11in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Number of pa</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ssengers</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.63in;left:5.03in;width:0.55in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">16. </span></SPAN><br/></div>
<div style="position:absolute;top:6.63in;left:5.03in;width:0.55in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">備考</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.76in;left:5.30in;width:0.46in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Remarks</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:6.58in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_85.png" />
<img style="position:absolute;top:6.58in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_86.png" />
<img style="position:absolute;top:6.58in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_87.png" />
<img style="position:absolute;top:6.58in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_88.png" />
<img style="position:absolute;top:6.58in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_89.png" />
<img style="position:absolute;top:6.58in;left:4.96in;width:3.54in;height:0.01in" src="documents/general_declaration/vi_90.png" />
<img style="position:absolute;top:6.58in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_91.png" />
<img style="position:absolute;top:6.59in;left:0.86in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_92.png" />
<img style="position:absolute;top:6.59in;left:2.91in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_93.png" />
<img style="position:absolute;top:6.59in;left:4.95in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_94.png" />
<img style="position:absolute;top:6.59in;left:8.50in;width:0.01in;height:0.62in" src="documents/general_declaration/vi_95.png" />
<div style="position:absolute;top:7.26in;left:2.40in;width:1.06in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">添付書類の枚数</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.22in;left:3.35in;width:0.12in;line-height:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000">※</span><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.25in;left:2.40in;width:1.06in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.39in;left:2.40in;width:0.98in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">A</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">tt</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ached document</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.39in;left:3.35in;width:0.12in;line-height:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000">※</span><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:MS-PMincho;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.50in;left:2.22in;width:1.42in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">I</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ndicate number of c</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">opies</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">）</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:7.21in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_96.png" />
<img style="position:absolute;top:7.21in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_97.png" />
<img style="position:absolute;top:7.21in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_98.png" />
<img style="position:absolute;top:7.21in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_99.png" />
<img style="position:absolute;top:7.21in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_100.png" />
<img style="position:absolute;top:7.21in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_101.png" />
<img style="position:absolute;top:7.22in;left:0.86in;width:0.01in;height:0.41in" src="documents/general_declaration/vi_102.png" />
<img style="position:absolute;top:7.22in;left:4.95in;width:0.01in;height:0.41in" src="documents/general_declaration/vi_103.png" />
<img style="position:absolute;top:7.22in;left:8.50in;width:0.01in;height:0.41in" src="documents/general_declaration/vi_104.png" />
<div style="position:absolute;top:7.67in;left:0.94in;width:0.82in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">17. </span></SPAN><br/></div>
<div style="position:absolute;top:7.68in;left:0.94in;width:0.82in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">積荷目録</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.81in;left:1.21in;width:0.92in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Car</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">go Declaration</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.67in;left:2.99in;width:0.96in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">18. </span></SPAN><br/></div>
<div style="position:absolute;top:7.68in;left:2.99in;width:0.96in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船用品目録</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.81in;left:3.26in;width:1.26in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Ship's Stores Declara</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">tion</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:7.63in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_105.png" />
<img style="position:absolute;top:7.63in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_106.png" />
<img style="position:absolute;top:7.63in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_107.png" />
<img style="position:absolute;top:7.63in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_108.png" />
<img style="position:absolute;top:7.63in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_109.png" />
<img style="position:absolute;top:7.63in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_110.png" />
<img style="position:absolute;top:7.63in;left:0.86in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_111.png" />
<img style="position:absolute;top:7.63in;left:2.91in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_112.png" />
<img style="position:absolute;top:7.63in;left:4.95in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_113.png" />
<img style="position:absolute;top:7.63in;left:8.50in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_114.png" />
<div style="position:absolute;top:8.19in;left:0.94in;width:0.96in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">19. </span></SPAN><br/></div>
<div style="position:absolute;top:8.20in;left:0.94in;width:0.96in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">乗組員名簿</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.33in;left:1.21in;width:0.51in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Crew List</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.19in;left:2.99in;width:0.82in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">20. </span></SPAN><br/></div>
<div style="position:absolute;top:8.20in;left:2.99in;width:0.82in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">旅客名簿</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.33in;left:3.26in;width:0.73in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Pa</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ssenger List</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.19in;left:5.03in;width:0.55in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">21. </span></SPAN><br/></div>
<div style="position:absolute;top:8.20in;left:5.03in;width:0.55in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">日付</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.33in;left:5.30in;width:0.32in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Date </span></SPAN><br/></div>
<div style="position:absolute;top:8.33in;left:5.30in;width:0.32in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:8.15in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_115.png" />
<img style="position:absolute;top:8.15in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_116.png" />
<img style="position:absolute;top:8.15in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_117.png" />
<img style="position:absolute;top:8.15in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_118.png" />
<img style="position:absolute;top:8.15in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_119.png" />
<img style="position:absolute;top:8.15in;left:4.96in;width:3.54in;height:0.01in" src="documents/general_declaration/vi_120.png" />
<img style="position:absolute;top:8.15in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_121.png" />
<img style="position:absolute;top:8.16in;left:0.86in;width:0.01in;height:0.51in" src="documents/general_declaration/vi_122.png" />
<img style="position:absolute;top:8.16in;left:2.91in;width:0.01in;height:0.51in" src="documents/general_declaration/vi_123.png" />
<img style="position:absolute;top:8.16in;left:4.95in;width:0.01in;height:0.51in" src="documents/general_declaration/vi_124.png" />
<img style="position:absolute;top:8.16in;left:8.50in;width:0.01in;height:0.51in" src="documents/general_declaration/vi_125.png" />
<div style="position:absolute;top:8.72in;left:0.94in;width:1.50in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">22. </span></SPAN><br/></div>
<div style="position:absolute;top:8.72in;left:0.94in;width:1.50in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">乗組員携帯品申告書</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.85in;left:1.21in;width:1.34in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Crew's</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> Effects Declara</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">tion</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.72in;left:2.99in;width:0.96in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">23. </span></SPAN><br/></div>
<div style="position:absolute;top:8.72in;left:2.99in;width:0.96in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">検疫明告書</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.85in;left:3.26in;width:1.56in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Mari</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">time Declarati</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">on of Health</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:8.67in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_126.png" />
<img style="position:absolute;top:8.67in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_127.png" />
<img style="position:absolute;top:8.67in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_128.png" />
<img style="position:absolute;top:8.67in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_129.png" />
<img style="position:absolute;top:8.67in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_130.png" />
<img style="position:absolute;top:8.67in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_131.png" />
<img style="position:absolute;top:8.68in;left:0.86in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_132.png" />
<img style="position:absolute;top:9.19in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_133.png" />
<img style="position:absolute;top:9.19in;left:0.86in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_134.png" />
<img style="position:absolute;top:9.19in;left:0.87in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_135.png" />
<img style="position:absolute;top:8.68in;left:2.91in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_136.png" />
<img style="position:absolute;top:9.19in;left:2.91in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_137.png" />
<img style="position:absolute;top:9.19in;left:2.91in;width:2.04in;height:0.01in" src="documents/general_declaration/vi_138.png" />
<img style="position:absolute;top:8.68in;left:4.95in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_139.png" />
<img style="position:absolute;top:9.19in;left:4.95in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_140.png" />
<img style="position:absolute;top:9.19in;left:4.96in;width:3.54in;height:0.01in" src="documents/general_declaration/vi_141.png" />
<img style="position:absolute;top:8.68in;left:8.50in;width:0.01in;height:0.52in" src="documents/general_declaration/vi_142.png" />
<img style="position:absolute;top:9.19in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_143.png" />
<img style="position:absolute;top:9.19in;left:8.50in;width:0.01in;height:0.01in" src="documents/general_declaration/vi_144.png" />
<div style="position:absolute;top:9.24in;left:0.86in;width:1.54in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">当局記入欄</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:9.25in;left:0.86in;width:1.54in;line-height:0.16in;"><DIV style="position:relative; left:0.77in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">For o</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">fficial use</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.44in;left:7.27in;width:0.82in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">24. </span></SPAN><br/></div>
<div style="position:absolute;top:9.44in;left:7.27in;width:0.82in;line-height:0.18in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">内航船舶</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.98in;left:0.86in;width:7.52in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PGothic;color:#000000">（</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Gothic;color:#000000">注</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PGothic;color:#000000">） </span></SPAN><br/></div>
<div style="position:absolute;top:10.98in;left:0.86in;width:7.52in;line-height:0.13in;"><DIV style="position:relative; left:0.37in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PGothic;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.98in;left:0.86in;width:7.52in;line-height:0.18in;"><DIV style="position:relative; left:0.45in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">1 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.98in;left:0.86in;width:7.52in;line-height:0.18in;"><DIV style="position:relative; left:0.59in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.98in;left:0.86in;width:7.52in;line-height:0.14in;"><DIV style="position:relative; left:0.66in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">※</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">の付されている項目については</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">記入不要</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV><DIV style="position:relative; left:0.27in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.13in;left:0.86in;width:7.52in;line-height:0.13in;"><DIV style="position:relative; left:0.36in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.13in;left:0.86in;width:7.52in;line-height:0.18in;"><DIV style="position:relative; left:0.45in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">2 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.13in;left:0.86in;width:7.52in;line-height:0.18in;"><DIV style="position:relative; left:0.59in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.13in;left:0.86in;width:7.52in;line-height:0.16in;"><DIV style="position:relative; left:0.66in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">傷病者を緊急の治療のために上陸させる目的で寄港し</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">直ちに出発する意図を有する船舶については</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、８</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PGothic;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">欄のうち</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">「</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">船舶</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PGothic;color:#000000"> </span><br/></DIV><DIV style="position:relative; left:0.55in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">の運航者の氏名又は名称及び住所</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">」</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">の記入不要</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.44in;left:1.13in;width:3.93in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:11.44in;left:1.13in;width:3.93in;line-height:0.13in;"><DIV style="position:relative; left:0.09in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:1.13in;width:3.93in;line-height:0.18in;"><DIV style="position:relative; left:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">3 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:1.13in;width:3.93in;line-height:0.18in;"><DIV style="position:relative; left:0.32in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:1.13in;width:3.93in;line-height:0.18in;"><DIV style="position:relative; left:0.39in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000">24.</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">欄には</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">内航船舶に該当する場合のみチェックを付すこと</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.72in;left:0.89in;width:2.98in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">Note</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PGothic;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:11.72in;left:0.89in;width:2.98in;line-height:0.12in;"><DIV style="position:relative; left:0.31in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PGothic;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.72in;left:0.89in;width:2.98in;line-height:0.16in;"><DIV style="position:relative; left:0.39in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">1 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.72in;left:0.89in;width:2.98in;line-height:0.16in;"><DIV style="position:relative; left:0.52in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.72in;left:0.89in;width:2.98in;line-height:0.16in;"><DIV style="position:relative; left:0.58in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">It is not nece</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ssary to fi</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ll in the item marked “</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PGothic;color:#000000">※</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">”</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.86in;left:1.13in;width:1.57in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:11.86in;left:1.13in;width:1.57in;line-height:0.12in;"><DIV style="position:relative; left:0.08in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.85in;left:1.13in;width:1.57in;line-height:0.16in;"><DIV style="position:relative; left:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">2</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">  With regard to ships ca</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.85in;left:1.43in;width:6.82in;line-height:0.15in;"><DIV style="position:relative; left:1.17in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">lling at ports in order to put ashore sick or injured persons for emergency medi</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">cal treatment and intending to leave</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">again i</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">mmediately</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">, </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">it is not nece</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ssary to fi</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ll in “Name and addre</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000">ss of ship’s Operator” of the column “8” </span></SPAN><br/></div>
<div style="position:absolute;top:11.99in;left:1.43in;width:6.82in;line-height:0.16in;"><DIV style="position:relative; left:5.13in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.99in;left:1.43in;width:6.82in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.28in;left:0.86in;width:6.88in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">備考</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:12.28in;left:0.86in;width:6.88in;line-height:0.13in;"><DIV style="position:relative; left:0.36in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.28in;left:0.86in;width:6.88in;line-height:0.18in;"><DIV style="position:relative; left:0.45in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">用紙の大きさは</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">、</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">日本産業規格</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">Ａ</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">列</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">４</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS Mincho;color:#000000">番とすること</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:MS-PMincho;color:#000000">。</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS-PMincho;color:#000000">                                           </span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:TimesNewRomanPSMT;color:#000000"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:9.33in;left:8.10in;width:0.41in;height:0.34in" src="documents/general_declaration/vi_145.png" />
<img style="position:absolute;top:9.33in;left:8.10in;width:0.42in;height:0.35in" src="documents/general_declaration/vi_146.png" />
</body>
</html>
